# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-17 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppy',
            name='update_at',
        ),
        migrations.AddField(
            model_name='puppy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
